[workspace]
members = ["crates/circuit", "crates/project", "crates/types"]

[workspace.dependencies]
sp1-zkvm = "=5.2.2"
sp1-sdk = { version = "=5.2.2", features = ["native-gnark"] }
serde = { version = "1.0", features = ["derive"] }
types = { path = "crates/types" }
bincode = "1.3.3"
celestia-grpc = "0.8.0"
prost = "0.13"
hex = "0.4"
tokio = { version = "1.45.0", features = [
    "sync",
    "macros",
    "io-util",
    "rt",
    "time",
    "rt-multi-thread",
], default-features = false }
