[package]
name = "circuit"
version = "0.1.0"
edition = "2024"

[dependencies]
sp1-zkvm.workspace = true
types.workspace = true
bincode.workspace = true
serde = { version = "1.0", features = ["derive"] }
